"""
Azure OpenAI agent handler — lightweight provider for the Research Analyst Bot.
Uses GPT-4o with function calling via raw REST API (no openai SDK — avoids
native binary dependencies that break on Lambda Linux runtime).
"""
import json
import os
import logging
import boto3
import requests

logger = logging.getLogger()
logger.setLevel(logging.INFO)

AZURE_ENDPOINT = os.environ["AZURE_OPENAI_ENDPOINT"].rstrip("/")
AZURE_API_KEY = os.environ["AZURE_OPENAI_API_KEY"]
AZURE_DEPLOYMENT = os.environ.get("AZURE_OPENAI_DEPLOYMENT", "gpt-4o")
AZURE_API_VERSION = os.environ.get("AZURE_OPENAI_API_VERSION", "2024-02-01")

CHAT_URL = (
    f"{AZURE_ENDPOINT}/openai/deployments/{AZURE_DEPLOYMENT}"
    f"/chat/completions?api-version={AZURE_API_VERSION}"
)
HEADERS = {
    "Content-Type": "application/json",
    "api-key": AZURE_API_KEY,
}

lambda_client = boto3.client(
    "lambda",
    region_name=os.environ.get("AWS_DEFAULT_REGION", "ap-southeast-1"),
)

# ── Tool definitions for GPT-4o function calling ──────────────────────────────

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "web_search",
            "description": "Search the live web for current technical information using Tavily.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "The search query"}
                },
                "required": ["query"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "s3_search",
            "description": "Search the internal S3 technical document library (Kubernetes, Docker, AWS Lambda guides).",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "The search query"}
                },
                "required": ["query"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "kb_search",
            "description": "Semantic search on the knowledge base for related content.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "The search query"}
                },
                "required": ["query"],
            },
        },
    },
]

SYSTEM_PROMPT = """You are an expert Technical Research Analyst. When a user sends you a research query, you MUST:

1. Search ALL THREE sources for every query:
   - web_search: Search the live web for current information
   - s3_search: Search the internal document library
   - kb_search: Query the knowledge base

2. After collecting results, synthesise into a comprehensive email-ready report using EXACTLY this format:

---

*SUBJECT:* [Concise descriptive subject line]

*Executive Summary*
[2-3 sentences covering the most important findings.]

*Key Findings*
- [Most important finding]
- [Second finding]
- [Third finding]
- [Fourth finding]
- [Fifth finding]

*Detailed Analysis*
[3-4 paragraphs of in-depth technical analysis synthesising all sources. Include specific details, best practices, and actionable recommendations.]

*Sources & References*

Web Sources:
- [Title] — [URL]

Internal Documents (S3):
- [Filename] — [What was found]

Knowledge Base:
- [Note if not available]

---
_Report generated by Technical Research Analyst — powered by Azure OpenAI_

3. Write in a professional tone suitable for senior software engineers."""


# ── Azure OpenAI REST helpers ─────────────────────────────────────────────────

def _chat(messages: list, tools: list = None, tool_choice: str = "auto") -> dict:
    """Call Azure OpenAI chat completions endpoint."""
    body = {
        "messages": messages,
        "max_tokens": 4000,
        "temperature": 0.1,
    }
    if tools:
        body["tools"] = tools
        body["tool_choice"] = tool_choice

    resp = requests.post(CHAT_URL, headers=HEADERS, json=body, timeout=60)
    resp.raise_for_status()
    return resp.json()


# ── Tool execution ────────────────────────────────────────────────────────────

def _invoke_lambda(function_name: str, query: str) -> dict:
    """Invoke a sibling tool Lambda and return parsed result."""
    payload = {
        "actionGroup": function_name,
        "apiPath": f"/{function_name.replace('research-agent-', '')}",
        "httpMethod": "GET",
        "parameters": [{"name": "query", "value": query}],
    }
    response = lambda_client.invoke(
        FunctionName=function_name,
        InvocationType="RequestResponse",
        Payload=json.dumps(payload),
    )
    result = json.loads(response["Payload"].read())
    try:
        body = result["response"]["responseBody"]["application/json"]["body"]
        return json.loads(body)
    except (KeyError, json.JSONDecodeError):
        return result


def _execute_tool(tool_name: str, arguments: dict) -> str:
    """Dispatch tool call and return string result for message history."""
    query = arguments.get("query", "")
    logger.info("Tool call: %s | query: %s", tool_name, query)

    if tool_name == "web_search":
        result = _invoke_lambda("research-agent-web-search", query)
    elif tool_name == "s3_search":
        result = _invoke_lambda("research-agent-s3-search", query)
    elif tool_name == "kb_search":
        result = {"note": "Knowledge Base not configured for Azure provider. Results from web and S3 only."}
    else:
        result = {"error": f"Unknown tool: {tool_name}"}

    return json.dumps(result)


# ── Agent loop ────────────────────────────────────────────────────────────────

def run_agent(query: str) -> str:
    """Run tool-calling loop until GPT-4o produces a final response."""
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": query},
    ]

    for iteration in range(5):
        logger.info("Agent iteration %d", iteration + 1)
        response = _chat(messages, tools=TOOLS)
        choice = response["choices"][0]
        message = choice["message"]

        # Append assistant message to history
        messages.append(message)

        tool_calls = message.get("tool_calls") or []

        # No tool calls — model produced final answer
        if not tool_calls:
            return message.get("content") or "No response generated."

        # Execute all tool calls and append results
        for tc in tool_calls:
            fn_name = tc["function"]["name"]
            try:
                args = json.loads(tc["function"]["arguments"])
            except (json.JSONDecodeError, KeyError):
                args = {}

            tool_result = _execute_tool(fn_name, args)
            messages.append({
                "role": "tool",
                "tool_call_id": tc["id"],
                "content": tool_result,
            })

    # Max iterations reached — request final synthesis without tools
    messages.append({
        "role": "user",
        "content": "Synthesise all gathered information into the final email-ready report now.",
    })
    final = _chat(messages)
    return final["choices"][0]["message"].get("content") or "Report generation failed."


# ── Lambda handler ────────────────────────────────────────────────────────────

def lambda_handler(event, context):
    """Entry point — called by webhook_handler via Lambda invoke."""
    query = event.get("query", "")
    if not query:
        return {"error": "No query provided"}
    try:
        report = run_agent(query)
        return {"report": report}
    except Exception as e:
        logger.exception("Azure agent error")
        return {"error": str(e)}
